# Generated by Django 5.0.3 on 2024-03-13 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articles_timestamp_articles_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='publish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
