# Generated by Django 5.0.3 on 2024-03-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='avtive',
            new_name='active',
        ),
    ]
