# Generated by Django 5.0.3 on 2024-03-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity_as_flout',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
